name: svorc_proto_v1
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  drift: ^2.20.2
  drift_flutter: ^0.1.0
  path_provider: ^2.1.4
  path: ^1.9.0
  sqlite3_flutter_libs: ^0.5.24
  sqlite3: ^2.4.6
  flutter_bloc: ^8.1.6
  jiffy: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  drift_dev: ^2.20.3
  build_runner: ^2.4.11
  mocktail: ^1.0.4

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
